package enums;

public enum AadhaarNumberTestDataType {
    EMPTY,
    LESS_THAN_12_DIGITS,
    MORE_THAN_12_DIGITS,
    EXACTLY_12_DIGITS,
    ALPHABETS_INCLUDED,
    SPECIAL_CHARACTERS,
    SPACES_INCLUDED,
    LEADING_ZEROS,
    ONLY_SPECIAL_CHARACTERS,
    NON_NUMERIC_STRING
}
