package enums;

public enum VoterIDTestDataType {
    EMPTY,
    NULL_VALUE,
    LESS_THAN_MIN,
    MORE_THAN_MAX,
    MIN_LENGTH,
    MAX_LENGTH,
    VALID_10_CHAR,
    VALID_16_CHAR,
    LOWERCASE,
    NUMERIC_ONLY,
    ALPHABET_ONLY,
    FORWARD_SLASH,
    MULTIPLE_FORWARD_SLASH,
    BACKWARD_SLASH,
    INVALID_SPECIAL_CHAR,
    SPACE_IN_INPUT,
    LEADING_TRAILING_SPACES,
    UNICODE_CHARACTERS,
    MIXED_CASE,
    VALID
}
